### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by takenalias** [matthew-larner/inception-mqtt#1]
Hi Matthew. I am loving the integration. Excellent job. Seems to be working well. 

One thing I finally worked out was that the name of the input / output in inception dictates the class in Home Assistant. 

If the name does have the words motion, door, cold, rex etc it will not match a class, and therefore get the class of None, so then it does not appear in HA, how this works seems fine, however, I think it would be good if the readme also states that for auto-discovery the inputs need to be named accordingly. Just thought it would be a lot easier if you made and pushed the changes rather than me making PR.

**Comment by matthew-larner** [comment]
Good point. Thanks for that. I've updated the docs to reflect this.
