### ISSUE TITLE
Lag 

### ISSUE THREAD

**Issue by FigJam23** [matthew-larner/inception-mqtt#4]
Hey thanks for a wicked addon for inception,
 I have set this up on hassio works well only using it via local network IP everything works as expected with the exception of being slow to respond. for example when clicking unlock it can take up to 5-10 seconds to actual unlock and update states.
this becomes issue with automations as state changes are slow to come through. when it does finally work and update date states into hassio via the recommended mqtt addon. it starts responding instantly. its like it goes to sleep and takes a while to wake up. network is good and no other issues running the likes of the paradox Pai Addon that works kind of similar .
any ideas on how i could make sure it runs as a high priority service to get close to live state changes and response's  

also Inception controller is connected via Wi-Fi but pings respond rapidly

**Comment by takenalias** [comment]
I found I had no issue and it was super responsive. Maybe there is something else at play here.

**Comment by matthew-larner** [comment]
It's super-fast on my setup. I'd recommend debugging it:
- try checking MQTT to see if the commands are coming through without delay.
- try connecting the controller via ethernet temporarily.
